# Mask R-CNN Demo

A quick intro to using the pre-trained model to detect and segment objects.

In [1]:
import os
import sys
import random
import math
import numpy as np
import skimage.io
import matplotlib
import matplotlib.pyplot as plt

# Root directory of the project
ROOT_DIR = os.path.abspath("../../")
print(ROOT_DIR)
# Import Mask RCNN
sys.path.append(ROOT_DIR)  # To find local version of the library
from mrcnn import utils
import mrcnn.model as modellib
from mrcnn import visualize
# Import COCO config
sys.path.append(os.path.join(ROOT_DIR, "samples/chips/"))  # To find local version
import chips_occlusion

get_ipython().run_line_magic('matplotlib', 'inline')

# Directory to save logs and trained model
MODEL_DIR = "/datasets/models/mrcnn/chips_occlusion/"

# Local path to trained weights file
MODEL_PATH = "/datasets/models/mrcnn/occlusion_fullnetwork/chips20200325T0525/mask_rcnn_chips_0160.h5"



/workspace/Mask_RCNN
Using TensorFlow backend.


## Configurations

We'll be using a model trained on the MS-COCO dataset. The configurations of this model are in the ```CocoConfig``` class in ```coco.py```.

For inferencing, modify the configurations a bit to fit the task. To do so, sub-class the ```CocoConfig``` class and override the attributes you need to change.

In [2]:
class InferenceConfig(chips_occlusion.ChipsConfig):
    # Set batch size to 1 since we'll be running inference on
    # one image at a time. Batch size = GPU_COUNT * IMAGES_PER_GPU
    GPU_COUNT = 1
    IMAGES_PER_GPU = 1

config = InferenceConfig()
config.display()


Configurations:
BACKBONE                       resnet101
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     1
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
COMPUTE_BACKBONE_SHAPE         None
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0.9
DETECTION_NMS_THRESHOLD        0.3
FPN_CLASSIF_FC_LAYERS_SIZE     1024
GPU_COUNT                      1
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_GPU                 1
IMAGE_CHANNEL_COUNT            3
IMAGE_MAX_DIM                  1024
IMAGE_META_SIZE                15
IMAGE_MIN_DIM                  800
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              square
IMAGE_SHAPE                    [1024 1024    3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.0001
LOSS_WEIGHTS                   {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_mask_loss': 1.0}
MASK_POOL_SIZE                 14
MASK_SHAPE        

## Create Model and Load Trained Weights

In [3]:
# Create model object in inference mode.
model = modellib.MaskRCNN(mode="inference", model_dir=MODEL_DIR, config=config)

# Load weights trained on MS-COCO
# model.load_weights(MODEL_PATH, by_name=True)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Instructions for updating:
box_ind is deprecated, use box_indices instead


Instructions for updating:
Use `tf.cast` instead.


In [4]:
# Chips Class names
# Index of the class in the list is its ID. For example, to get ID of
# the teddy bear class, use: class_names.index('teddy bear')
class_names = ['BG', 'full mask', 'occluded']

## Run Object Detection

In [5]:
# import os
# import sys
# import random
# import math
# import numpy as np
# import skimage.io
# import matplotlib
# import matplotlib.pyplot as plt
# Load a random image from the images folder
# Directory of images to run detection on
image = skimage.io.imread("/datasets/idNerd/Chips/CHIP_STACK_01_00009.jpg")
print(image[0][0])
# Run detection
results = model.detect([image], verbose=1)

# Visualize results
r = results[0]
visualize.display_instances(image, r['rois'], r['masks'], r['class_ids'], 
                            class_names, r['scores'])

[45 31 44]
Processing 1 images
image                    shape: (3104, 4192, 3)       min:    0.00000  max:  255.00000  uint8
Lossy conversion from float64 to uint8. Range [-123.7, 151.1]. Convert image to uint8 prior to saving to suppress this warning.
backboneshape: [[256 256]
 [128 128]
 [ 64  64]
 [ 32  32]
 [ 16  16]]
[[0 0]
 [0 0]
 [0 0]
 [0 4]
 [0 4]]
[[45.254834 22.627417]
 [32.       32.      ]
 [22.627417 45.254834]
 [45.254834 22.627417]
 [32.       32.      ]]
box_centers[0]: [0 0]
box_sizes[0]  : [45.254834 22.627417]
box_centers[1]: [0 0]
box_sizes[1]  : [32. 32.]
boxes[0]:    [-22.627417  -11.3137085  22.627417   11.3137085]
[[0 0]
 [0 0]
 [0 0]
 [0 8]
 [0 8]]
[[90.50966799 45.254834  ]
 [64.         64.        ]
 [45.254834   90.50966799]
 [90.50966799 45.254834  ]
 [64.         64.        ]]
box_centers[0]: [0 0]
box_sizes[0]  : [90.50966799 45.254834  ]
box_centers[1]: [0 0]
box_sizes[1]  : [64. 64.]
boxes[0]:    [-45.254834 -22.627417  45.254834  22.627417]
[[ 0  0]
 

UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv1/convolution}}]]
	 [[mrcnn_detection/Reshape_1/_1507]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv1/convolution}}]]
0 successful operations.
0 derived errors ignored.

In [6]:
# # Load a random image from the images folder
# # Directory of images to run detection on
# IMAGE_DIR = "/datasets/Chips/model_testing"
# file_names = next(os.walk(IMAGE_DIR))[2]
# image = skimage.io.imread(os.path.join(IMAGE_DIR, random.choice(file_names)))

# # Run detection
# results = model.detect([image], verbose=1)

# # Visualize results
# r = results[0]
# visualize.display_instances(image, r['rois'], r['masks'], r['class_ids'], 
#                             class_names, r['scores'])

In [7]:
# import glob
# file_names = glob.glob1(IMAGE_DIR, '*.jpg')
# for file_name in file_names: 
#     # if file_name.split('.')[-1]
#     image = skimage.io.imread(os.path.join(IMAGE_DIR, file_name))

#     # Run detection
#     results = model.detect([image], verbose=1)

#     # Visualize results
#     r = results[0]
#     visualize.display_instances(image, r['rois'], r['masks'], r['class_ids'], 
#                                 class_names, r['scores'])

In [8]:
results

NameError: name 'results' is not defined