In [1]:
import os, sys
import json


In [2]:
def openJsonFile(path):
    with open(path, 'r') as inFile:
        return json.load(inFile)

In [3]:
dataDir = "/datasets/idNerd/preprocess/"
pyInputPath = os.path.join(dataDir, "pythonInputs.json")
goInputPath = os.path.join(dataDir, "goInputs.json")
pyInput = openJsonFile(pyInputPath)
goInput = openJsonFile(goInputPath)

pyMeta = pyInput['data']['metas']
goMeta = goInput['metas']

In [4]:
pyMeta = pyInput['data']['metas']
goMeta = goInput['metas']

print(pyMeta)
print(goMeta)

[[0.0, 3104.0, 4192.0, 3.0, 1024.0, 1024.0, 3.0, 133.0, 0.0, 891.0, 1024.0, 0.24427480916030533, 0.0, 0.0, 0.0]]
[[0, 3104, 4192, 3, 1024, 1024, 3, 133, 0, 891, 1024, 0.24427481, 0, 1, 2]]


In [5]:
import numpy as np
pyAnchors = np.array(pyInput['data']['anchors'])
goAnchors = np.array(goInput['anchors'])

In [6]:
pyAnchors.shape

(1, 261888, 4)

In [7]:
goAnchors.shape

(1, 261888, 4)

In [8]:
diffAnchors = pyAnchors - goAnchors

In [9]:
diffAnchors.sum()

-0.00013762161540853413

In [11]:
pyAnchors.strides

(8380416, 32, 8)

In [12]:
goAnchors.strides

(8380416, 32, 8)

In [13]:
np.where(diffAnchors == diffAnchors.max())

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([261152, 261200, 261248, 261296, 261344, 261633, 261636, 261639,
        261642, 261645]),
 array([3, 3, 3, 3, 3, 2, 2, 2, 2, 2]))

In [21]:
i = 1
print(goAnchors[0, i, :])
print(pyAnchors[0, i, :])

[-0.02211869 -0.00714928  0.02114117  0.0139919 ]
[-0.01564027 -0.01564027  0.01466276  0.01466276]


In [59]:
pyImg = np.array(pyInput['data']['image'])
goImg = np.array(goInput['image'])

In [60]:
pyImg.shape

(1, 1024, 1024, 3)

In [61]:
goImg.shape

(1, 1024, 1024, 3)

In [62]:
diffImg = pyImg - goImg
diffImg.sum()

-1134910.9771387859

In [63]:
pyR = pyImg[0, 133:891, :, 0]
goR = goImg[0, 133:891, :, 0]
diffR = pyR - goR
diffR.sum()

-384901.03484579787

In [64]:
import pandas as pd
dfpyR = pd.DataFrame(pyR)
dfgoR = pd.DataFrame(goR)


In [65]:
print(dfpyR.head())
print(dfgoR.head())


0     1     2     3      4     5     6     7      8     9     ...  1014  \
0 -69.7 -65.7 -78.7 -52.7  -46.7 -58.7 -80.7 -71.7  -81.7 -61.7  ...  79.3   
1 -70.7 -65.7 -94.7 -48.7  -70.7 -59.7 -70.7 -76.7  -77.7 -73.7  ...  87.3   
2 -64.7 -59.7 -55.7 -60.7 -106.7 -65.7 -61.7 -64.7 -103.7 -84.7  ...  74.3   
3 -59.7 -86.7 -96.7 -70.7  -83.7 -63.7 -70.7 -83.7  -71.7 -76.7  ...  90.3   
4 -59.7 -47.7 -87.7 -80.7  -76.7 -73.7 -59.7 -66.7  -66.7 -56.7  ...  79.3   

   1015  1016  1017  1018  1019  1020   1021  1022  1023  
0  76.3  86.3  90.3  90.3  79.3  85.3   81.3  19.3 -22.7  
1  81.3  82.3  74.3  59.3  83.3  91.3   82.3  29.3 -40.7  
2  74.3  72.3  76.3  80.3  76.3  76.3   70.3  18.3 -20.7  
3  81.3  91.3  88.3  85.3  72.3  93.3  103.3  -0.7 -39.7  
4  79.3  88.3  81.3  78.3  76.3  94.3   67.3 -20.7 -47.7  

[5 rows x 1024 columns]
        0         1          2          3           4          5     \
0 -68.025925 -64.11040 -76.904340 -51.700485  -47.704147 -58.262497   
1 -68.519090 

In [66]:
print(dfpyR.tail())
print(dfgoR.tail())

0      1      2     3     4     5     6     7     8     9     ...  \
753  130.3  131.3  129.3  80.3  43.3   4.3 -15.7 -33.7 -17.7 -20.7  ...   
754  131.3  126.3  131.3  51.3  13.3 -21.7  -1.7 -26.7  -6.7 -24.7  ...   
755  129.3  128.3  127.3  43.3  -6.7 -29.7  -1.7 -26.7 -25.7 -33.7  ...   
756  129.3  131.3   75.3  49.3   0.3 -19.7 -23.7 -10.7 -41.7 -25.7  ...   
757  130.3  128.3   46.3  -4.7 -25.7 -54.7 -52.7 -18.7 -35.7 -26.7  ...   

      1014   1015   1016   1017   1018   1019   1020   1021   1022   1023  
753  112.3  130.3  126.3  123.3  111.3  112.3  120.3  123.3  122.3  122.3  
754  114.3  126.3  129.3  131.3  123.3  128.3  122.3  125.3  120.3  127.3  
755  126.3  129.3  130.3  129.3  128.3  129.3  116.3  123.3  129.3  131.3  
756  114.3  119.3  130.3  122.3  116.3  123.3  126.3  128.3  119.3  112.3  
757  113.3  121.3  127.3  121.3  111.3  122.3  117.3  116.3  114.3  123.3  

[5 rows x 1024 columns]
          0           1           2          3          4          5     \

In [67]:
pyImg[0, 133, 0]

array([-69.7, -90.8, -74.9])

In [68]:
goImg[0, 133, 0]

array([-68.025925, -90.93623 , -71.12998 ])

In [69]:
pyG = pyImg[0, 133:891, :, 1]
goG = goImg[0, 133:891, :, 1]
diffG = pyG - goG
diffG.sum()

-379873.48528524867

In [70]:
diffG.max()

54.033939000000004

In [71]:
np.where(diffG == diffG.max())

(array([431]), array([393]))

In [72]:
diffImg[0, 15+133, 11+891]

array([-7.55713 ,  1.650882,  7.02588 ])